CREATE TABLE users
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username                 TEXT NOT NULL UNIQUE,

    email_salt               TEXT,
    email_verification_code  TEXT,
    email_zk_proof           BYTEA,
    email_zk_id              BIGINT,

    phone_salt               TEXT,
    phone_verification_code  TEXT,
    phone_zk_proof           BYTEA,
    phone_zk_id              BIGINT,

    public_key               BYTEA,

    salt                     TEXT,
    iteration_count          BIGINT,
    server_key               TEXT,
    stored_key               TEXT,

    telegram_session_id_hash BYTEA
);

CREATE TABLE clients
(
    id                     TEXT PRIMARY KEY,

    secret                 TEXT,
    name                   TEXT,
    redirect_uri           TEXT,
    backend_uri            TEXT UNIQUE,

    username               TEXT NOT NULL UNIQUE,

    salt                   TEXT NOT NULL,
    iteration_count        BIGINT,
    server_key             TEXT,
    stored_key             TEXT,

    x509_certificate_bytes BYTEA
);

CREATE TABLE user_metadata
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    display_name             TEXT NOT NULL DEFAULT '',
    color                    TEXT NOT NULL DEFAULT '',
    bio                      TEXT NOT NULL DEFAULT '',

    is_email_verified        BOOLEAN     NOT NULL DEFAULT FALSE,
    is_phone_number_verified BOOLEAN     NOT NULL DEFAULT FALSE,

    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE client_balance
(
    id                    BIGSERIAL PRIMARY KEY,

    client_id             TEXT NOT NULL UNIQUE,

    balance_wei           NUMERIC(78, 0),
    status                TEXT DEFAULT 'zeroed',

    last_usage_updated_at TIMESTAMPTZ
);

CREATE TABLE client_payment_receipt
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    client_id       TEXT NOT NULL,

    paid_amount_wei NUMERIC(78, 0),
    paid_at         TIMESTAMPTZ,
    tx_id           TEXT
);

CREATE TABLE email_verification_data
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id           BIGINT      NOT NULL UNIQUE,

    salt              TEXT        NOT NULL,
    email             TEXT        NOT NULL,
    verification_code TEXT        NOT NULL,

    expires_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE phone_number_verification_data
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id           BIGINT      NOT NULL UNIQUE,

    salt              TEXT        NOT NULL,
    phone_number      TEXT        NOT NULL,
    verification_code TEXT        NOT NULL,

    expires_at        TIMESTAMPTZ NOT NULL
);

CREATE TABLE zk_snarks_key_pairs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    proving_key   BYTEA NOT NULL,
    verifying_key BYTEA NOT NULL
);

CREATE TABLE oauth_authorization_codes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code         TEXT        NOT NULL UNIQUE,

    client_id    TEXT        NOT NULL,
    user_id      BIGINT      NOT NULL,

    redirect_uri TEXT        NOT NULL,
    scopes       TEXT        NOT NULL,
    nonce        TEXT,

    expires_at   BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
